echo "PROMPT"
cat prompt.txt
echo "------------------------------------------"
echo "model: gemma-3-270m-it with adapters:"
python -m mlx_lm generate --model ./models/gemma-3-270m-it --max-tokens 4096 --system-prompt "You are a PostgresSQL expert. You take user's query and return Valid SQL, don't add any filler" --adapter-path adapters/270m --prompt "$(cat prompt.txt)"
echo "------------------------------------------"
echo "model: gemma-3-270m-it w/0 adapters:"
python -m mlx_lm generate --model ./models/gemma-3-270m-it --max-tokens 4096 --system-prompt "You are a PostgresSQL expert. You take user's query and return Valid SQL, don't add any filler" --prompt "$(cat prompt.txt)"
echo "------------------------------------------"
echo "model: LFM2.5-350M w/0 adapters:"
python -m mlx_lm generate --model ./models/LFM2.5-350M --max-tokens 4096 --system-prompt "You are a PostgresSQL expert. You take user's query and return Valid SQL, don't add any filler" --prompt "$(cat prompt.txt)"
echo "------------------------------------------"
echo "model: gemma-3-1b-it with adapters:"
python -m mlx_lm generate --model ./models/gemma-3-1b-it --max-tokens 4096 --system-prompt "You are a PostgresSQL expert. You take user's query and return Valid SQL, don't add any filler" --adapter-path adapters/1b --prompt "$(cat prompt.txt)"
echo "------------------------------------------"
echo "model: gemma-3-1b-it w/0 adapters:"
python -m mlx_lm generate --model ./models/gemma-3-1b-it --max-tokens 4096 --system-prompt "You are a PostgresSQL expert. You take user's query and return Valid SQL, don't add any filler" --prompt "$(cat prompt.txt)"
